<div class='col'><div class='card h-100'>
<img src='{{picture}}' class='card-img-top img-fluid img-thumbnail'>
<div class='card-body text-center'><h5 class='card-title'>{{fullname}}</h5>
<button type='button' class='my-2 btn btn-primary btn-sm w-50'>Messages</button> <!--ADD JS/AJAX later for these two buttons -->
<br>
<button type='button' class='my-2 btn btn-primary btn-sm w-50'>Unfriend</button>
</div></div></div>