
<!--internal page stylesheet-->
<link rel="stylesheet" type="text/css" href="css/index_landing.css"> 

<br>
<main class='container'>
<div class='row justify-content-center'>
<div class='col-12 pt-3' id='landing-img'></div>
<div class='col-10 offset-2 pt-3'>
  <h2 class='text-primary'> {{ appName }} </h2>
  <h5>Connect with friends and the world around you on {{appName}}.</h5>
</div>
</div>
</main>
