
<br><br>
<section class="container">

<form method="post" action="index.php?reqPage=login">

  <div class="row mb-3 justify-content-center">
    <div class="col-6">
      <input type="text" class="form-control" name="user" id="user" placeholder="Username" minlength="5" maxlength="20" pattern="[a-z0-9]{5,20}" title="username is between 5 and 20 characters long and include only lowercase letters and digits" required> 
    </div>
  </div>

  <div class="row mb-3 justify-content-center">
    <div class="col-6">
      <input type="password" class="form-control" name="password" id="password" name="password" minlength="5" maxlength="20" placeholder="Password" required>
    </div>
  </div>
  
  <div class="row mb-3 justify-content-center">
    <div class="col-6">
      <button type="submit" class="btn btn-primary col-12" id="signupBtn">Log in</button>
    </div>
  </div>

</form>
</section>
