<!--start row, embeds data for who the chat is with-->
<div class='row my-2 py-2 conversationRow' data-chatWith='{{chatWith}}'> 
     
  <div class='col-5'><!--photo-->
    <img src='{{picture}}' class='rounded-circle me-2' width='110px' height='110px'>
  </div>

  <div class='col-7 d-flex flex-column justify-content-start align-items-start'><!--name, msg, last-->
    <div class='h5'>{{name}}</div>
    <div class='small'>{{message}}</div>
    <div class='small text-muted align-self-end mt-auto'>{{ago}}</div>
  </div>

</div> <!--close row-->